---
# tasks file for nexus3-rest
- name: Get existing repo
  uri:
    url: "{{ nexus_api_url }}/beta/repositories"
    user: "{{ nexus_user }}"
    password: "{{ nexus_password }}"
    force_basic_auth: yes
    return_content: yes
    status_code:
    - 200
  register: repos

- name: debug repos
  debug:
    var:
      repos.content
  when: DEBUG|int > 2

- name: Check repo exists
  set_fact:
    repo_format: "{{item.format}}"
    repo_type: "{{item.type}}"
    repo_name: "{{item.name}}"
  with_items:
    "{{ repos.content }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.name == repo.name

- name: Set docker repos list
  set_fact:
    nexus_repo: "{{ _nexus_repos_defaults[repo.format] | combine(repo, recursive=True) }}"

- name: "Show {{ repo_name }}"
  debug:
    var:
      nexus_repo
  when: DEBUG is defined

- name: "create repo {{ repo.name }}"
  uri:
    url: "{{ nexus_api_url }}/beta/repositories/{{ repo.format }}/{{ repo.type }}"
    method: POST
    body_format: json
    body: "{{ nexus_repo }}"
    user: "{{ nexus_user }}"
    password: "{{ nexus_password }}"
    force_basic_auth: yes
    return_content: yes
    status_code:
    - 201
  when: not repo_name is defined

- name: "update repo {{ repo.name }}"
  uri:
    url: "{{ nexus_api_url }}/beta/repositories/{{ repo.format }}/{{ repo.type }}/{{ repo.name }}"
    method: PUT
    body_format: json
    body: "{{ nexus_repo|to_json }}"
    user: "{{ nexus_user }}"
    password: "{{ nexus_password }}"
    force_basic_auth: yes
    return_content: yes
    status_code:
    - 204
  when: repo_name is defined

- name: Parse roles
  set_fact:
    nexus_roles: |
      {% set result = [] -%}
      {% for role in DSO_roles.keys() -%}
        {% set privN = [] -%}
        {% for priv in DSO_roles[role].privileges -%}
          {% set ignored = privN.append(priv.format(
            tech="{{ repo.format }}", 
            repo="{{ repo.name }}")) -%}
        {% endfor -%}
        {% set ingored = result.append({'id': role, 
          'name': role, 
          'description': DSO_roles[role].description,
          'source': 'default', 
          'privileges': privN }) -%}
      {% endfor -%}
      {{ result }}

- name: Check existing roles
  uri:
    url: "{{ nexus_api_url }}/beta/security/roles/{{ item.id }}"
    user: "{{ nexus_user }}"
    password: "{{ nexus_password }}"
    force_basic_auth: yes
    return_content: yes
    status_code:
    - 200
    - 404
  loop:
    "{{ nexus_roles }}"
  register: roles

- name: "Show roles"
  debug: var=roles
  when: DEBUG is defined and DEBUG|int > 1

- name: "Update privileges for {{ repo_name }}"
  set_fact:
    roles_to_update: |
      {% set result = [] -%}
      {% set ingored = result.append({'id': item.item.id, 
        'name': item.item.name, 
        'privileges': item.item.privileges | union(item.json.privileges) | unique }) -%}
      {{ roles_to_update + [result] }}
  with_items:
    "{{ roles.results }}"
  loop_control:
    label: "{{ item.item.name }}"
  when: item.status == 200

- name: "Create privileges for {{ repo_name }}"
  set_fact:
    roles_to_create: |
      {% set result = [] -%}
      {% set ingored = result.append({'id': item.item.id, 
        'name': item.item.name, 
        'description': item.item.description, 
        'source': item.item.source, 
        'privileges': item.item.privileges }) -%}
      {{ roles_to_create + [result] }}
  with_items:
    "{{ roles.results }}"
  loop_control:
    label: "{{ item.item.name }}"
  when: item.status == 404

- name: "Show privileges for {{ repo_name }}"
  debug:
    var:
      roles_to_update
  when: DEBUG is defined

- name: "Show privileges for {{ repo_name }}"
  debug:
    var:
      roles_to_create
  when: DEBUG is defined

- name: "Create roles"
  uri:
    url: "{{ nexus_api_url }}/beta/security/roles"
    method: POST
    body_format: json
    body: "{{ item|to_json }}"
    user: "{{ nexus_user }}"
    password: "{{ nexus_password }}"
    force_basic_auth: yes
    return_content: yes
    status_code:
    - 200
  with_items:
    "{{ roles_to_create }}"
  when: roles_to_create is defined and roles_to_create|length > 0

- name: "Update roles"
  uri:
    url: "{{ nexus_api_url }}/beta/security/roles/{{ item.id }}"
    method: PUT
    body_format: json
    body: "{{ item|to_json }}"
    user: "{{ nexus_user }}"
    password: "{{ nexus_password }}"
    force_basic_auth: yes
    return_content: yes
    status_code:
    - 204
  with_items:
    "{{ roles_to_update }}"
  when: roles_to_update is defined and roles_to_update|length > 0
